import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class InvTable extends javax.swing.JFrame {
static Connection con;
    static PreparedStatement pst;
    /**
     * Creates new form InvTable
     */
    public InvTable() {
        initComponents();
        show_data();
    }
    
    
    public void show_data()
{   
    try{
        con=DB.getCon();
        
        String sql="select item_desc,bar_code,mrp,sale_price,item_id from m_item";
         
             pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
           
            inv_tbl.setModel(DbUtils.resultSetToTableModel(rs));
            
    }
    catch(Exception e)
    {
         
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inv_tbl = new javax.swing.JTable();
        c1 = new javax.swing.JComboBox<>();
        TF1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Invoice Table");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        inv_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item_desc", "Barcode", "M.R.P", "Sale Price", "Item ID"
            }
        ));
        inv_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inv_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(inv_tbl);

        c1.setEditable(true);
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item_desc", "Barcode", "Sale_Price", "Item_Id" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jLabel1.setText("Filter");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIKE" }));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("                                              Invoice Generation");
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(137, 137, 137))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inv_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inv_tblMouseClicked
        int a=inv_tbl.getSelectedRow();

        String i_desc=inv_tbl.getValueAt(a, 0).toString();
        String bar=inv_tbl.getValueAt(a, 1).toString();
        String mrp=inv_tbl.getValueAt(a, 2).toString();
        String sp=inv_tbl.getValueAt(a, 3).toString();
        InvoicGen ig=new InvoicGen();
        System.out.println("gaya gaya");
        System.out.println("mrp is"+mrp);
        if(sp.equals(null) || mrp.equals(null))
        {
            JOptionPane.showMessageDialog(this, "Please enter MRP or Sale Price!");
        }
        else
        {
        ig.bar1=bar;
        ig.i_desc1=i_desc;
        ig.mrp1=mrp;
        ig.sp22=sp;
        ig.p=1;
        }
        //      ig.refresh(bar,mrp,sp,i_desc,p);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_inv_tblMouseClicked

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
    }//GEN-LAST:event_c1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //        java.awt.event.KeyEvent evt1;
        String s=c1.getSelectedItem().toString();
        String d=TF1.getText();
        //      if()
        if(s=="Item_desc")
        {
            //
            try{
                con=DB.getCon();
                
                //         if(s=="Fname")
                //         {
                    //                    String tushar="select * from i_master where   like '"+d+"%'";
                    String qry="select  item_desc,bar_code,mrp,sale_price,item_id from m_item where item_desc like'"+d+"%'";
                    //             String tushar="select grp_id,grp_desc from group_new where grp_id='"+d+"'";

                     pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    inv_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch(Exception e)
                {

                }
            }
            if(s=="Barcode")
            {
                System.out.println("helo");
                String d1=TF1.getText();
                try{
                    con=DB.getCon();
                    

                    //                    String tushar="select grp_id,grp_desc from group_new where grp_desc like '"+d1+"%'";
                    String qry="select  item_desc,bar_code,mrp,sale_price,item_id from m_item where bar_code like'"+d1+"%'";
                     pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    inv_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch(Exception e)
                {

                }
                
            }
            if(s=="Sale_Price")
            {
                String d2=TF1.getText();
                try{
                    con=DB.getCon();
                    

                    //                    String tushar="select grp_id,grp_desc from group_new where grp_desc like '"+d1+"%'";
                    String qry="select  item_desc,bar_code,mrp,sale_price,item_id from m_item where sale_price like'"+d2+"%'";
                     pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    inv_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch(Exception e)
                {

                }
            }
            if(s=="Item_Id")
            {
                String d2=TF1.getText();
                try{
                    con=DB.getCon();
                    

                    //                    String tushar="select grp_id,grp_desc from group_new where grp_desc like '"+d1+"%'";
                    String qry="select  item_desc,bar_code,mrp,sale_price,item_id from m_item where item_id like'"+d2+"%'";
                     pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    inv_tbl.setModel(DbUtils.resultSetToTableModel(rs));
                        con.close();
                }
                catch(Exception e)
                {
                    System.out.println("item id"+e);
                }
            }
          
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF1;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JTable inv_tbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
