import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.beans.Statement;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JApplet;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import java.math.BigDecimal;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */

public class Pament_reciept extends javax.swing.JFrame {

    static Connection con;
    static PreparedStatement pst;
    
    
    /**
     * Creates new form Pament_reciept
     */
    public Pament_reciept() {
        initComponents();
        filter.setSelectedItem(null);
        filter.addItem("");
        paym.setSelectedItem(null);
        paym.addItem("");
        show_data();
        typepaymod_ins();
    }
    public void rec_tot()
    {
        float sum=0,g=0;
        String s=filter.getSelectedItem().toString();
        String s1=filter1.getSelectedItem().toString();
        String fv=forval.getSelectedItem().toString();
        String d=search_bx.getText();
        System.out.println("in no ");
          
          
                 System.out.println("in no ");
               for(int i=0;i<custdet_tbl.getRowCount();i++)
              {
                g=Float.parseFloat(custdet_tbl.getValueAt(i, 4).toString());
                
               sum+=g;
              }
////                 System.out.println(""+g);
         System.out.println("sum isss"+sum);
             recv.setText(""+sum);
             
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        custdet_tbl = new javax.swing.JTable();
        filter = new javax.swing.JComboBox<>();
        search_bx = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        forval = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        paytab = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        paym = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        pamt = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        cstend = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        ccn = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        cqno = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        cqdt = new com.toedter.calendar.JDateChooser();
        bnk1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        inv_no = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        custidtxt = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        custaddrtxt = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        custnmtxt = new javax.swing.JTextField();
        Addpanel = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Savepanel = new javax.swing.JPanel();
        Save = new javax.swing.JButton();
        Help = new javax.swing.JButton();
        Fresh = new javax.swing.JButton();
        Quit = new javax.swing.JButton();
        amtp = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        filter1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        recv = new javax.swing.JLabel();
        totpayrc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payment Receipt");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        custdet_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Inv_no", "Inv_dt", "Customer_id", "Customer_name", "pay_amt", "Customer_addr"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        custdet_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                custdet_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(custdet_tbl);

        filter.setEditable(true);
        filter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inv_no", "Inv_date", "pay_amt", "Customer_id", "Customer_name", "Customer_addr", " " }));
        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });

        search_bx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Filter");

        forval.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        forval.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIKE", ">", "<" }));

        paytab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SNo.", "Pay Mode", "Pay Amt", "Cash", "Refund", "CC No", "Bank", "Cheque No.", "Cheque dt"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(paytab);

        jPanel4.setOpaque(false);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel30.setText("PAY MODES");

        paym.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel31.setText("AMOUNT");

        pamt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pamt.setText("0.00");
        pamt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pamtKeyPressed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel32.setText("CASH TEND");

        cstend.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cstend.setText("00.00");
        cstend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cstendActionPerformed(evt);
            }
        });
        cstend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cstendKeyPressed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel33.setText("CC No.");

        ccn.setEditable(false);
        ccn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel34.setText("CHQ. NO");

        cqno.setEditable(false);
        cqno.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel35.setText("CHQ. DATE");

        cqdt.setDateFormatString("d/MM/y");
        cqdt.setEnabled(false);

        bnk1.setEditable(false);
        bnk1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel36.setText("BANK");

        inv_no.setEditable(false);
        inv_no.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        inv_no.setEnabled(false);

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel37.setText("INVOICE NO.");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel38.setText("CUSTOMER ID");

        custidtxt.setEditable(false);
        custidtxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        custidtxt.setEnabled(false);

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel39.setText("CUSTOMER ADDR.");

        custaddrtxt.setEditable(false);
        custaddrtxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        custaddrtxt.setEnabled(false);
        custaddrtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custaddrtxtActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel40.setText("CUSTOMER NAME");

        custnmtxt.setEditable(false);
        custnmtxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        custnmtxt.setEnabled(false);
        custnmtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custnmtxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inv_no, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(paym, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(jLabel30)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel37)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(pamt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel31)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cstend, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel32)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(ccn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel33)))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bnk1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel36))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel38)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel40)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cqno, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel34)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(cqdt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel35)
                                        .addGap(41, 41, 41))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(custidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(custnmtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(custaddrtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bnk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ccn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cstend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paym, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cqdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cqno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inv_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel40))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custnmtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custaddrtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        Addpanel.setOpaque(false);

        add.setText("Add");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addKeyPressed(evt);
            }
        });

        jButton6.setText("Quit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddpanelLayout = new javax.swing.GroupLayout(Addpanel);
        Addpanel.setLayout(AddpanelLayout);
        AddpanelLayout.setHorizontalGroup(
            AddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddpanelLayout.createSequentialGroup()
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        AddpanelLayout.setVerticalGroup(
            AddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(AddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Savepanel.setOpaque(false);

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Help.setText("Help");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });

        Fresh.setText("Fresh");
        Fresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FreshActionPerformed(evt);
            }
        });

        Quit.setText("Quit");
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SavepanelLayout = new javax.swing.GroupLayout(Savepanel);
        Savepanel.setLayout(SavepanelLayout);
        SavepanelLayout.setHorizontalGroup(
            SavepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SavepanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Quit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Help, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fresh, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SavepanelLayout.setVerticalGroup(
            SavepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SavepanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(SavepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Help, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fresh, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        amtp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        amtp.setOpaque(true);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Amt to Pay");

        filter1.setEditable(true);
        filter1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        filter1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        filter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Payment Done");

        recv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        recv.setOpaque(true);

        totpayrc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totpayrc.setText("TOT AMOUNT TO BE RECV.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Addpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Savepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(totpayrc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recv, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(amtp, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(forval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(search_bx, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filter1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filter1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(search_bx, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(forval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totpayrc)
                        .addComponent(recv, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(amtp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Addpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(Savepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void close()
     {
         WindowEvent closeWindow=new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
         Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
     }
    public void show_data()
    {
        try {
            con=DB.getCon();
            String qry="select h.inv_no,h.inv_dt,h.cust_id,h.cust_nm,h.amt_pay,h.inv_cust_addr,h.payment_mode,p.pay_mod from t_inv_hdr h,t_inv_paymode p where h.inv_no=p.inv_no";
            pst=con.prepareStatement(qry);
            ResultSet rs=pst.executeQuery();
           
            custdet_tbl.setModel(DbUtils.resultSetToTableModel(rs));
            

        } catch (Exception e) {
        }
    }
    
    public void typepaymod_ins() 
             {
                try{
        
            con=DB.getCon();
            
            
            String quer="select pay_mod_id from m_pay_mod";
            pst=con.prepareStatement(quer);
            java.sql.ResultSet rs=pst.executeQuery();

            while(rs.next())
      {
//          String sr=
          paym.addItem(rs.getString("pay_mod_id"));
//     
           
      }
          }
    catch (Exception e) {
          JOptionPane.showMessageDialog(null, e);
        } 
             }
    
    public void add_row1(Object[] row1)
{
    DefaultTableModel df=(DefaultTableModel)paytab.getModel();
    df.addRow(row1);
   
   
}

    
    float upramt, smam,refam,nicamt;
public void matc()
{
      nicamt=Float.parseFloat(pamt.getText());
//    float namt=Float.parseFloat(pamt.getText());
     refam=Float.parseFloat(cstend.getText());
     upramt=Float.parseFloat(amtp.getText());
     smam=0;
          int row2=paytab.getRowCount();
          for(int y=0;y<row2;y++)
          {
              float aah=Float.parseFloat(paytab.getValueAt(y,2).toString());
              smam+=aah;
          }
    
}    

public void to_sum_pt1()
       {
          float aamo=Float.parseFloat(amtp.getText());
          float sm=0;
          int row2=paytab.getRowCount();
          for(int y=0;y<row2;y++)
          {
              float ah=Float.parseFloat(paytab.getValueAt(y,2).toString());
              sm+=ah;
          }
          float pyamt=aamo-sm;
           System.out.println("in func"+pyamt);
          pamt.setText(""+pyamt);
      }


public void save()
{
    
//     String invn,sno,barcod,itemnm,qt,mr,pri,dis,disam,gs,ces,am,itmid;
    String paymo,payam,paycs,payrf,cno,bn,chqn,chqd;
    DefaultTableModel dtm= (DefaultTableModel) paytab.getModel();
    try {
        
               
          con=DB.getCon();
            
        for(int l=0;l<dtm.getRowCount();l++){
           
//            invn=dtm.getValueAt(l, 0).toString();
            paymo=dtm.getValueAt(l, 1).toString();
            payam=dtm.getValueAt(l, 2).toString();
            paycs=dtm.getValueAt(l, 3).toString();
            payrf=dtm.getValueAt(l, 4).toString();
            cno=dtm.getValueAt(l, 5).toString();
            bn=dtm.getValueAt(l, 6).toString();
            chqn=dtm.getValueAt(l, 7).toString();
            chqd=dtm.getValueAt(l, 8).toString();
            System.out.println("tt " +payam);
            System.out.println("dd "+paymo);
            System.out.println("in pay11");
//        String quer="insert into t_inv_paymode (pay_mod,pay_amt,pay_cash,pay_ref,ccno,bnk,cqno,cqdt,inv_no) values(?,?,?,?,?,?,?,?,?)";
        String qry="update t_inv_paymode set pay_mod='"+paymo+"',pay_amt='"+payam+"',pay_cash='"+paycs+"',pay_ref='"+payrf+"',"
                + "ccno='"+cno+"',bnk='"+bn+"',cqno='"+chqn+"',cqdt='"+chqd+"' where inv_no="+inv_no.getText();

//            String quer="insert into m_item(item_id,item_desc,item_type_id,item_type_name,group_id,group_desc,manuf_id,manuf_name) values (?,?,?,?,?,?,?,?)";
//            String quer="insert into i_master(item_id,active_yn) values (?,?)";
              pst=con.prepareStatement(qry);
//              pst.setString(1,paymo);
//              pst.setString(2,payam);
//              pst.setString(3,paycs);
//              pst.setString(4,payrf);
//              pst.setString(5,cno);
//              pst.setString(6,bn);
//              pst.setString(7,chqn);
//              pst.setString(8,chqd);
//              pst.setString(9,inv_no.getText());
              System.out.println("in pay22");
              pst.executeUpdate();
              System.out.println("in pay223");
              
         
        }
        String qry="update t_inv_hdr set payment_mode='Yes' where inv_no="+inv_no.getText();     
         pst=con.prepareStatement(qry);
         pst.executeUpdate();
         JOptionPane.showMessageDialog(this, "Updated");
        con.close();
    } catch (Exception e) 
    {
        JOptionPane.showMessageDialog(null, "in catch block"+e);
    }
    
}




    private void custdet_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custdet_tblMouseClicked
//             if(evt.getClickCount()==2)
        
//            evt.consume();
          
        
        DefaultTableModel model=(DefaultTableModel)custdet_tbl.getModel();
        int selectedRowIndex=custdet_tbl.getSelectedRow();
        
        inv_no.setText(model.getValueAt(selectedRowIndex, 0).toString());
        custidtxt.setText(model.getValueAt(selectedRowIndex, 2).toString());
        custnmtxt.setText(model.getValueAt(selectedRowIndex, 3).toString());
        pamt.setText(model.getValueAt(selectedRowIndex, 4).toString());
        amtp.setText(model.getValueAt(selectedRowIndex, 4).toString());
        custaddrtxt.setText(model.getValueAt(selectedRowIndex, 5).toString());
        
        model.removeRow(selectedRowIndex);
        
    
         rec_tot();

    

    }//GEN-LAST:event_custdet_tblMouseClicked

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed

        //        String s1=c1.getSelectedItem().toString();
        //        if(s1=="Group_desc")
        //        {
            //
            //            jLabel1.setText("hello!");
            //        }

        // TODO add your handling code here:
    }//GEN-LAST:event_filterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

                java.awt.event.KeyEvent evt1;
        String s=filter.getSelectedItem().toString();
        String s1=filter1.getSelectedItem().toString();
        String fv=forval.getSelectedItem().toString();
        String d=search_bx.getText();
        System.out.println("in no ");
          float sum=0,g=0;
          
             
        if(s=="Inv_no" && s1=="No")
        {
            sum=0;
            //
            try{
                con=DB.getCon();
                //         if(s=="Fname")
                //         {
                    //                    String tushar="select * from i_master where   like '"+d+"%'";
                    String qry="select inv_no,inv_dt,cust_id,cust_nm,amt_pay,inv_cust_addr,payment_mode from t_inv_hdr where inv_no like'"+d+"%' and payment_mode='No'";
                    //             String tushar="select grp_id,grp_desc from group_new where grp_id='"+d+"'";

                    pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    custdet_tbl.setModel(DbUtils.resultSetToTableModel(rs));
                 
                }
                catch(Exception e)
                {

                }
            rec_tot();
            }
            if(s=="Inv_date" && s1=="No")
            {
                System.out.println("helo");
                String d1=search_bx.getText();
                try{
                    con=DB.getCon();
                    //                    String tushar="select grp_id,grp_desc from group_new where grp_desc like '"+d1+"%'";
                    String qry="select inv_no,inv_dt,cust_id,cust_nm,amt_pay,inv_cust_addr,paymode_mode,payment_mode  from t_inv_hdr where inv_dt like'"+d1+"%' and payment_mode='No'";
                    pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    custdet_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch(Exception e)
                {

                }
                rec_tot();
            }
            if(s=="pay_amt" && s1=="No")
            {
                System.out.println("in pay_amt");
                String d2=search_bx.getText();
                try{
                    con=DB.getCon();

                    //                    String tushar="select grp_id,grp_desc from group_new where grp_desc like '"+d1+"%'";
                    String qry="select inv_no,inv_dt,cust_id,cust_nm,amt_pay,inv_cust_addr,payment_mode from t_inv_hdr where amt_pay like'"+d2+"%' and payment_mode='No'";
                    pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    custdet_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch(Exception e)
                {

                }
                rec_tot();
            }
            if(s=="pay_amt" && fv==">" && s1=="No")
            {
                System.out.println("in pay_amt");
                String d2=search_bx.getText();
                try{
                    con=DB.getCon();

                    //                    String tushar="select grp_id,grp_desc from group_new where grp_desc like '"+d1+"%'";
                    String qry="select inv_no,inv_dt,cust_id,cust_nm,amt_pay,inv_cust_addr,payment_mode from t_inv_hdr where amt_pay >'"+d2+"' and payment_mode='No'";
                    pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    custdet_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch(Exception e)
                {

                }
                rec_tot();
            }
            if(s=="pay_amt" && fv=="<" && s1=="No")
            {
                System.out.println("in pay_amt");
                String d2=search_bx.getText();
                try{
                    con=DB.getCon();

                    //                    String tushar="select grp_id,grp_desc from group_new where grp_desc like '"+d1+"%'";
                    String qry="select inv_no,inv_dt,cust_id,cust_nm,amt_pay,inv_cust_addr,payment_mode from t_inv_hdr where amt_pay <'"+d2+"' and payment_mode='No'";
                    pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    custdet_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch(Exception e)
                {

                }
                rec_tot();
            }
            if(s=="Customer_id" && s1=="No")
            {
                String d2=search_bx.getText();
                try{
                    con=DB.getCon();
                    //                    String tushar="select grp_id,grp_desc from group_new where grp_desc like '"+d1+"%'";
                    String qry="select inv_no,inv_dt,cust_id,cust_nm,amt_pay,inv_cust_addr,payment_mode from t_inv_hdr where cust_id like'"+d2+"%' and payment_mode='No'";
                    pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    custdet_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch(Exception e)
                {

                }
                rec_tot();
            }
            if(s=="Customer_name" && s1=="No")
            {
                String d2=search_bx.getText();
                try{
                    con=DB.getCon();
                    //                    String tushar="select grp_id,grp_desc from group_new where grp_desc like '"+d1+"%'";
                    String qry="select inv_no,inv_dt,cust_id,cust_nm,amt_pay,inv_cust_addr,payment_mode from t_inv_hdr where cust_name like'"+d2+"%' and payment_mode='No'";
                    pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    custdet_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch(Exception e)
                {

                }
                rec_tot();
            }
            if(s=="Customer_addr" && s1=="No")
            {
                String d2=search_bx.getText();
                try{
                    con=DB.getCon();
                    //                    String tushar="select grp_id,grp_desc from group_new where grp_desc like '"+d1+"%'";
                    String qry="select inv_no,inv_dt,cust_id,cust_nm,amt_pay,inv_cust_addr,payment_mode from t_inv_hdr where inv_cust_addr like'"+d2+"%' and payment_mode='No'";
                    pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    custdet_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch(Exception e)
                {

                }
                rec_tot();
            }
            
 
/************************************YES**********************/
            
            if(s=="Inv_no" && s1=="Yes" && fv=="LIKE")
            {
                System.out.println("in inv no yes like");
            //
                String d3=search_bx.getText();
            try{
                con=DB.getCon();
                //         if(s=="Fname")
                //         {
                    //                    String tushar="select * from i_master where   like '"+d+"%'";
                    String qry="select inv_no,inv_dt,cust_id,cust_nm,amt_pay,inv_cust_addr,payment_mode from t_inv_hdr where inv_no like'"+d3+"%' and payment_mode='Yes'";
                    //             String tushar="select grp_id,grp_desc from group_new where grp_id='"+d+"'";

                    pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    custdet_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch(Exception e)
                {

                }
            rec_tot();
            }
            if(s=="Inv_date" && fv=="LIKE" && s1=="Yes")
            {
                totpayrc.setText("Total Amt Paid");
                System.out.println("helo");
                String d1=search_bx.getText();
                try{
                    con=DB.getCon();
                    //                    String tushar="select grp_id,grp_desc from group_new where grp_desc like '"+d1+"%'";
                    String qry="select inv_no,inv_dt,cust_id,cust_nm,amt_pay,inv_cust_addr,payment_mode  from t_inv_hdr where inv_dt like'"+d1+"%' and payment_mode='Yes'";
                    pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    custdet_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch(Exception e)
                {

                }
                rec_tot();
            }
            if(s=="pay_amt" && s1=="Yes")
            {
                System.out.println("in pay_amt");
                totpayrc.setText("Total Amt Paid");
                String d2=search_bx.getText();
                try{
                    con=DB.getCon();

                    //                    String tushar="select grp_id,grp_desc from group_new where grp_desc like '"+d1+"%'";
                    String qry="select inv_no,inv_dt,cust_id,cust_nm,amt_pay,inv_cust_addr,payment_mode from t_inv_hdr where amt_pay like'"+d2+"%' and payment_mode='Yes'";
                    pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    custdet_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch(Exception e)
                {

                }
                rec_tot();
            }
            if(s=="pay_amt" && fv==">" && s1=="Yes")
            {
                totpayrc.setText("Total Amt Paid");
                System.out.println("in pay_amt");
                String d2=search_bx.getText();
                System.out.println("fsd  "+d2);
                try{
                    con=DB.getCon();

                    //                    String tushar="select grp_id,grp_desc from group_new where grp_desc like '"+d1+"%'";
                    String qry="select inv_no,inv_dt,cust_id,cust_nm,amt_pay,inv_cust_addr,payment_mode from t_inv_hdr where amt_pay >'"+d2+"' and payment_mode='Yes'";
                    pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    custdet_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch(Exception e)
                {

                }
                rec_tot();
            }
            if(s=="pay_amt" && fv=="<" && s1=="yes")
            {
                totpayrc.setText("Total Amt Paid");
                System.out.println("in pay_amt");
                String d2=search_bx.getText();
                try{
                    con=DB.getCon();

                    //                    String tushar="select grp_id,grp_desc from group_new where grp_desc like '"+d1+"%'";
                    String qry="select inv_no,inv_dt,cust_id,cust_nm,amt_pay,inv_cust_addr,payment_mode from t_inv_hdr where amt_pay <'"+d2+"' and payment_mode='Yes'";
                    pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    custdet_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch(Exception e)
                {

                }
                rec_tot();
            }
            if(s=="Customer_id" && s1=="Yes")
            {
                totpayrc.setText("Total Amt Paid");
                String d2=search_bx.getText();
                try{
                    con=DB.getCon();
                    //                    String tushar="select grp_id,grp_desc from group_new where grp_desc like '"+d1+"%'";
                    String qry="select inv_no,inv_dt,cust_id,cust_nm,amt_pay,inv_cust_addr,payment_mode from t_inv_hdr where cust_id like'"+d2+"%' and payment_mode='Yes'";
                    pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    custdet_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch(Exception e)
                {

                }
                rec_tot();
            }
            if(s=="Customer_name" && s1=="Yes")
            {
                totpayrc.setText("Total Amt Paid");
                String d2=search_bx.getText();
                try{
                    con=DB.getCon();
                    //                    String tushar="select grp_id,grp_desc from group_new where grp_desc like '"+d1+"%'";
                    String qry="select inv_no,inv_dt,cust_id,cust_nm,amt_pay,inv_cust_addr,payment_mode from t_inv_hdr where cust_name like'"+d2+"%' and payment_mode='Yes'";
                    pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    custdet_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch(Exception e)
                {

                }
                rec_tot();
            }
            if(s=="Customer_addr" && s1=="Yes")
            {
                totpayrc.setText("Total Amt Paid");
                String d2=search_bx.getText();
                try{
                    con=DB.getCon();
                    //                    String tushar="select grp_id,grp_desc from group_new where grp_desc like '"+d1+"%'";
                    String qry="select inv_no,inv_dt,cust_id,cust_nm,amt_pay,inv_cust_addr,payment_mode from t_inv_hdr where inv_cust_addr like'"+d2+"%' and payment_mode='Yes'";
                    pst=con.prepareStatement(qry);
                    ResultSet rs=pst.executeQuery();

                    custdet_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch(Exception e)
                {

                }
                rec_tot();
            }
//           
           
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void pamtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pamtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pamtKeyPressed

    private void cstendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cstendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cstendActionPerformed

    private void cstendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cstendKeyPressed
        // TODO add your handling code here:
        float amo=Float.parseFloat(pamt.getText());
        float damo=Float.parseFloat(amtp.getText());
        float cste=Float.parseFloat(cstend.getText());
        float dif=0;
        float re;
        matc();
        if(cste<amo)
        {
            re=(cste-amo)*(-1);
        }
        else
        {
            re=cste-amo;
        }

        String ccc=ccn.getText();
        String gg="cheq";
        String gc="cash";
        String gh="cc/dc";
        String p=paym.getSelectedItem().toString();
        String cc="";
        String bn=bnk1.getText();
        String cq=cqno.getText();
        System.out.println(p);
        //        Date d=new Date();
        if(damo>amo)
        {
            dif=damo-amo;
        }

        System.out.println("hhhhh76");

        int s=paytab.getRowCount()+1;
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {     System.out.println("hhhhh");
            //
            if(smam==upramt)
            {
                JOptionPane.showMessageDialog(null, "Amount Matched!!!");
            }

            else
            {
                if(p.equals(gg))
                {SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");

                    String dd=sdf.format(cqdt.getDate());

                    add_row1 (new Object[]{
                        s,
                        p,
                        amo,
                        cstend.getText(),
                        cstend.getText(),
                        cc,
                        bn,
                        cq,
                        dd

                    });
                    System.out.println("kkkk");
                }

                else if(p.equals(gh))
                {

                    add_row1 (new Object[]{
                        s,
                        p,
                        amo,
                        cstend.getText(),
                        cstend.getText(),
                        ccc,
                        //               cc,
                        //               cc,
                        //               cc
                    });
                    System.out.println("okokokok");
                }
                else if(p.equals(gc))
                {
                    if(refam<nicamt)
                    {
                        JOptionPane.showMessageDialog(this, "Cash Tend Cannot Be < PAY AMOUNT!! ");
                    }
                    else{
                        add_row1 (new Object[]{
                            s,
                            p,
                            amo,
                            cstend.getText(),
                            re,
                            cc,
                            cc,
                            cc,
                            cc

                        });
                    }}
                    else
                    {
                        add_row1 (new Object[]{
                            s,
                            p,
                            amo,
                            cstend.getText(),
                            cstend.getText(),
                            cc,
                            cc,
                            cc,
                            cc
                        });
                    }
                    System.out.println("hjhjhjh");
                    to_sum_pt1();

                    cstend.setText("00.00");

                }
            }

    }//GEN-LAST:event_cstendKeyPressed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        Addpanel.hide();
//        editenabTru();
        Savepanel.show();
    
        
        filter.requestFocusInWindow();
        //        cust_ins();

    }//GEN-LAST:event_addActionPerformed

    private void addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_addKeyPressed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_SaveActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_HelpActionPerformed

    private void FreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FreshActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_FreshActionPerformed

    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        // TODO add your handling code here:
        close();
        setDefaultCloseOperation(dashboard.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_QuitActionPerformed

    private void custaddrtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custaddrtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custaddrtxtActionPerformed

    private void custnmtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custnmtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custnmtxtActionPerformed

    private void filter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filter1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
                close();
        setDefaultCloseOperation(dashboard.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pament_reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pament_reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pament_reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pament_reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pament_reciept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Addpanel;
    private javax.swing.JButton Fresh;
    private javax.swing.JButton Help;
    private javax.swing.JButton Quit;
    private javax.swing.JButton Save;
    private javax.swing.JPanel Savepanel;
    private javax.swing.JButton add;
    private javax.swing.JLabel amtp;
    private javax.swing.JTextField bnk1;
    private javax.swing.JTextField ccn;
    private com.toedter.calendar.JDateChooser cqdt;
    private javax.swing.JTextField cqno;
    private javax.swing.JTextField cstend;
    private javax.swing.JTextField custaddrtxt;
    private javax.swing.JTable custdet_tbl;
    private javax.swing.JTextField custidtxt;
    private javax.swing.JTextField custnmtxt;
    private javax.swing.JComboBox<String> filter;
    private javax.swing.JComboBox<String> filter1;
    private javax.swing.JComboBox<String> forval;
    private javax.swing.JTextField inv_no;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pamt;
    private javax.swing.JComboBox<String> paym;
    private javax.swing.JTable paytab;
    private javax.swing.JLabel recv;
    private javax.swing.JTextField search_bx;
    private javax.swing.JLabel totpayrc;
    // End of variables declaration//GEN-END:variables
}
